spring:
  application:
    name: credits-service
  data:
    mongodb:
      database: CreditService
      port: 27017
      host: localhost
server:
  port: 8011
eureka:
  client: 
    serviceUrl:
      defaultZone: http://localhost:8090/eureka/
