spring:
  application:
    name: customers-service
  data:
    mongodb:
      database: CustomerService
      port: 27017
      host: localhost
server:
  port: 8001
eureka:
  client: 
    serviceUrl:
      defaultZone: http://localhost:8090/eureka/
