server:
  port: 8050

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/Account/**
        - id: customers-service
          uri: lb://customers-service
          predicates:
            - Path=/Customers/**
        - id: retirement-service
          uri: lb://retirement-service
          predicates:
            - Path=/retirement/**    
        - id: credits-service
          uri: lb://credits-service
          predicates:
            - Path=/Credits_Service/**   
        - id: deposit-service
          uri: lb://deposit-service
          predicates:
            - Path=/deposits/**  
