server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8090/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: deposit-service
          uri: lb://deposit-service
          predicates:
            - Path=/deposit/**
        