spring:
  application:
    name: retirement-service
  data:
    mongodb:
      database: RetirementService
      port: 27017
      host: localhost
server:
  port: 8005
eureka:
  client: 
    serviceUrl:
      defaultZone: http://localhost:8090/eureka/